image: Ubuntu

stack: jdk 11

build: off

artifacts:
  - path: /home/appveyor/projects/aqa-homework-3/build/reports/
    name: reports

install:
  - java -jar ./artifacts/app-mbank.jar -port=7777 &

build_script:
  - ./gradlew test -Dselenide.headless=true -Dselenide.disable-gpu=-true --info